notifications:
  email:
    on_success: never
    on_failure: change
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a1da3bd88506f40132bf
    on_success: change
    on_failure: always
    on_start:   never

os: osx

language: node_js
node_js: 10

install:
  - npm install

stages:
  - lint
  - test
  - name: deploy
    if: branch = stable

jobs:
  include:
    - stage: lint
      node_js: 10
      script: npm run lint

    - stage: test
      node_js: 10
      script: npm run make
      
    - # This next job runs w/ test
      node_js: 10
      script: npm run make-mas

    - stage: deploy
      if: branch = stable
      node_js: 10
      script: npm run publish
