notifications:
  email:
    on_success: never
    on_failure: change
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a1da3bd88506f40132bf
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
    
os: osx

language: node_js
node_js: 8


install:
  - npm install

stages:
  - test
  - name: deploy
    if: branch = stable

jobs:
  include:
    - stage: test
      node_js: 8
      script: npm run make
    - # this next job runs w/ test
      node_js: 8
      script: npm run make-mas
    - stage: deploy
      if: branch = stable
      node_js: 8
      script: npm run publish
