environment:
  nodejs_version: "10"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i

build_script:
  - npm run build

test_script:
  - node --version
  - npm --version
  - npm test
