platform:
  - x64

install:
  - ps: Install-Product node 10 x64
  - npm install -g electron-forge
  - npm install

for:
-
  branches:
    only:
      - stable

  configuration: Release
  build_script:
    - npm run publish
-
  configuration: Debug
  build_script:
    - npm run make

test: "off"
